# Generated by Django 2.1.1 on 2018-09-30 08:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2018, 9, 30, 11, 21, 39, 764419))),
                ('status', models.CharField(choices=[('AC', 'Active'), ('BA', 'Banned'), ('DU', 'DUE'), ('AD', 'Adjudicated')], default='AC', max_length=2)),
                ('last_bidder', models.ForeignKey(default=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller', to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_bidder', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='EN', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
