# Generated by Django 2.1.1 on 2018-09-23 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YAASApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 19, 33, 9, 740873)),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('BA', 'Banned'), ('DU', 'DUE'), ('AD', 'Adjudicated')], default='AC', max_length=2),
        ),
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='EN', max_length=2),
        ),
    ]
